controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_effort_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_group_effort_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - lf_hip_joint
      - lf_upper_leg_joint
      - lf_lower_leg_joint
      - rf_hip_joint
      - rf_upper_leg_joint
      - rf_lower_leg_joint
      - lb_hip_joint
      - lb_upper_leg_joint
      - lb_lower_leg_joint
      - rb_hip_joint
      - rb_upper_leg_joint
      - rb_lower_leg_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      lf_hip_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      lf_upper_leg_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      lf_lower_leg_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      rf_hip_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      rf_upper_leg_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      rf_lower_leg_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      lb_hip_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      lb_upper_leg_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      lb_lower_leg_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      rb_hip_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      rb_upper_leg_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      rb_lower_leg_joint: {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
